[book]
authors = ["soleuniverse"]
language = "fr"
src = "src"
title = "Anki Manual i18n POC"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.xgettext]
optional = true
pot-file = "messages.pot"
granularity = 0