[book]
authors = ["soleuniverse"]
language = "en"
src = "src"
title = "Anki Manual i18n POC"

[rust]
edition = "2024"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
additional-css = ["theme/css/language-picker.css"]
